{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.tls -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certificate
  namespace: {{ .Release.namespace }}
spec:
  secretName: grafana-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: {{ .Values.ingress.hostname }}
  dnsNames:
    - {{ .Values.ingress.hostname }}
{{- end}}
{{- end}}