{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.tls -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: {{ .Release.namespace }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-admin
  namespace: {{ .Release.namespace }}
data:
  users: {{ .Values.ingress.traefikUser}}
{{- end }}
{{- end }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-auth
  namespace: {{ .Release.namespace }}
spec:
  basicAuth:
    secret: traefik-admin