{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.tls -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
    namespace: {{ .Release.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
{{- end }}