{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.tls -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: {{ .Release.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-auth
  namespace: {{ .Release.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
spec:
  basicAuth:
    secret: traefik-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-admin
  namespace: {{ .Release.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "3"
data:
  users: {{ .Values.ingress.traefikUser}}
{{- end }}
{{- end }}