{{- if .Values.ingress.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: {{ .Release.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.hostname }}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      services:
        - kind: TraefikService
          name: api@internal
      {{- if .Values.ingress.tls }}
      middlewares:
        - name: redirect-https
          namespace: {{ .Release.namespace }}
      {{- end }}
---
{{- if .Values.ingress.tls }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-ssl
  namespace: {{ .Release.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.hostname }}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      services:
        - kind: TraefikService
          name: api@internal
      middlewares:
        - name: traefik-auth
          namespace: {{ .Release.namespace }}
  tls:
    secretName: traefik-certificate
{{- end }}
{{- end }}
